# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
    - nightly
matrix:
  allow_failures:
    - julia: nightly    
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("PATHSolver");  Pkg.build("PATHSolver"); Pkg.test("PATHSolver", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'cd(Pkg.dir("PATHSolver")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
